'use client';

import { useEffect, useRef, useState } from 'react';
import { GoogleGenAI, Modality } from '@google/genai';
import { Mic, MicOff } from 'lucide-react';
import { Button } from '@/components/ui/button';

type LiveVoiceButtonProps = { onTurn: (userText: string, assistantText: string) => void; disabled?: boolean; resetKey?: number };
type LiveMessage = { serverContent?: { inputTranscription?: { text?: string }; outputTranscription?: { text?: string }; modelTurn?: { parts?: Array<{ inlineData?: { data?: string } }> }; interrupted?: boolean; turnComplete?: boolean } };

function base64ToInt16(base64:string){const binary=atob(base64);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const view=new DataView(bytes.buffer);const samples=new Int16Array(bytes.byteLength/2);for(let i=0;i<samples.length;i++)samples[i]=view.getInt16(i*2,true);return samples;}
function int16ToBase64(samples:Int16Array){const bytes=new Uint8Array(samples.length*2);const view=new DataView(bytes.buffer);for(let i=0;i<samples.length;i++)view.setInt16(i*2,samples[i],true);let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary);}

export default function LiveVoiceButton({onTurn,disabled=false,resetKey=0}:LiveVoiceButtonProps){
 const [live,setLive]=useState(false);const sessionRef=useRef<any>(null);const streamRef=useRef<MediaStream|null>(null);const inputContextRef=useRef<AudioContext|null>(null);const outputContextRef=useRef<AudioContext|null>(null);const processorRef=useRef<ScriptProcessorNode|null>(null);const sourceRef=useRef<MediaStreamAudioSourceNode|null>(null);const sinkRef=useRef<GainNode|null>(null);const outputSourcesRef=useRef<Set<AudioBufferSourceNode>>(new Set());const nextOutputTimeRef=useRef(0);const userTextRef=useRef('');const assistantTextRef=useRef('');
 const stopOutput=()=>{for(const source of outputSourcesRef.current){try{source.stop();}catch{}}outputSourcesRef.current.clear();nextOutputTimeRef.current=outputContextRef.current?.currentTime??0;};
 const stop=()=>{stopOutput();processorRef.current?.disconnect();sourceRef.current?.disconnect();sinkRef.current?.disconnect();streamRef.current?.getTracks().forEach(t=>t.stop());sessionRef.current?.close?.();inputContextRef.current?.close().catch(()=>undefined);outputContextRef.current?.close().catch(()=>undefined);processorRef.current=null;sourceRef.current=null;sinkRef.current=null;streamRef.current=null;sessionRef.current=null;inputContextRef.current=null;outputContextRef.current=null;userTextRef.current='';assistantTextRef.current='';setLive(false);};
 useEffect(()=>()=>stop(),[]);useEffect(()=>{if(live)stop();},[resetKey]);
 const playPcm=(base64:string)=>{const context=outputContextRef.current;if(!context)return;const samples=base64ToInt16(base64);const buffer=context.createBuffer(1,samples.length,24000);const channel=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)channel[i]=samples[i]/32768;const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);outputSourcesRef.current.add(source);source.onended=()=>outputSourcesRef.current.delete(source);const start=Math.max(context.currentTime+.02,nextOutputTimeRef.current);source.start(start);nextOutputTimeRef.current=start+buffer.duration;};
 const start=async()=>{if(disabled||live)return;try{const tokenResponse=await fetch('/api/gemini/live-token',{method:'POST',cache:'no-store'});if(!tokenResponse.ok)throw new Error('Unable to provision Gemini Live session.');const {token,model}=await tokenResponse.json();const ai=new GoogleGenAI({apiKey:token});const session=await ai.live.connect({model,config:{responseModalities:[Modality.AUDIO],inputAudioTranscription:{},outputAudioTranscription:{},sessionResumption:{}},callbacks:{onmessage:(message:LiveMessage)=>{const content=message.serverContent;if(!content)return;if(content.inputTranscription?.text)userTextRef.current+=content.inputTranscription.text;if(content.outputTranscription?.text)assistantTextRef.current+=content.outputTranscription.text;if(content.interrupted)stopOutput();for(const part of content.modelTurn?.parts??[])if(part.inlineData?.data)playPcm(part.inlineData.data);if(content.turnComplete){const user=userTextRef.current.trim();const assistant=assistantTextRef.current.trim();if(user||assistant)onTurn(user,assistant);userTextRef.current='';assistantTextRef.current='';}},onerror:(event:unknown)=>console.error('Gemini Live error:',event),onclose:()=>setLive(false)}});const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const inputContext=new AudioContext({sampleRate:16000});const outputContext=new AudioContext({sampleRate:24000});await inputContext.resume();await outputContext.resume();const source=inputContext.createMediaStreamSource(stream);const processor=inputContext.createScriptProcessor(4096,1,1);const sink=inputContext.createGain();sink.gain.value=0;processor.onaudioprocess=e=>{const channel=e.inputBuffer.getChannelData(0);const pcm=new Int16Array(channel.length);for(let i=0;i<channel.length;i++)pcm[i]=Math.max(-1,Math.min(1,channel[i]))*32767;session.sendRealtimeInput({audio:{data:int16ToBase64(pcm),mimeType:'audio/pcm;rate=16000'}});};source.connect(processor);processor.connect(sink);sink.connect(inputContext.destination);sessionRef.current=session;streamRef.current=stream;inputContextRef.current=inputContext;outputContextRef.current=outputContext;sourceRef.current=source;processorRef.current=processor;sinkRef.current=sink;nextOutputTimeRef.current=outputContext.currentTime;setLive(true);}catch(error){console.error('Unable to start JUSU AI Live:',error);stop();window.alert('JUSU AI live voice could not start. Please check microphone permission and try again.');}};
 return <Button type="button" size="icon" variant={live?'destructive':'ghost'} onClick={live?stop:start} disabled={disabled} aria-label={live?'Stop live conversation':'Start live conversation'} title={live?'Stop live conversation':'Start live conversation'}>{live?<MicOff/>:<Mic/>}</Button>;
}
